# Home Assistant configuration
homeassistant:
  debug: true

# Logger configuration
logger:
  default: info
  logs:
    custom_components.keypad_manager: debug

# Core integrations (without go2rtc dependency issues)
frontend:
automation:
script:
scene:
person:
backup:
onboarding:
lovelace:
mobile_app:
notify:
tts:
todo:
