default_config:

# Home Assistant configuration
homeassistant:
  debug: true

# Logger configuration
logger:
  default: info
  logs:
    custom_components.keypad_manager: debug

automation: !include automations.yaml